# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Punchcard Polyphony
email: michael.berkowitz@gmail.com
description: Musings on code, music, and probably some other stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.songsaboutsnow.com"
twitter_username: hal678
github_username:  mikowitz

# Build settings
markdown: kramdown
